#!/bin/sh

cp nginx/default.conf.example nginx/default.conf
cp connect/config/production.json.example connect/config/production.json

os=$(uname)
host=$NODE_HOST;
# : is 'do nothing' command. it emits the value, then tries to run it
: ${host:=laptop-connect.anvil.io};

echo $host

if [ "$os" = "Linux" ]; then
  replace_host=s/HOST/$host/g
  sed -i "$replace_host" nginx/default.conf

  sed -i "$replace_host" connect/config/production.json
else
  replace_host=s/HOST/$host/g
  perl -p -i -e "$replace_host" default.conf

  perl -p -i -e "$replace_host" connect/config/production.json
fi
