#!/bin/sh

cp default.conf.example default.conf

os=$(uname)
host=$NODE_ENV; 
# : is 'do nothing' command. it emits the value, then tries to run it
: ${host:=laptop-connect.anvil.io};

echo $host

if [ "$os" = "Linux" ]; then
  gateway=$(ip -o -4 addr show docker0| awk -F '[ /]+' '/global/ {print $4}')
  replace_gateway=s/GATEWAY/$gateway/g
  sed -i "$replace_gateway" default.conf

  replace_host=s/ENV/$host/g
  sed -i "$replace_host" default.conf
else
  gateway=$(boot2docker ip)
  replace_gateway=s/GATEWAY/$gateway/g
  perl -p -i -e "$replace_gateway" efault.conf

  replace_host=s/ENV/$host/g
  perl -p -i -e "$replace_host" efault.conf
fi

